@startsalt
title Basket page
{+
  Иванов Иван Иванович | {
  ^UserID^ Корзина^ Заказы^ Уведомления^
  }
  [Каталог]
  ----
  {^<b>Список Товаров в корзине:</b>
	  {SI
	  <b> ИД | <b> Описание товара | <b> Количество	| <b> Стоимость (руб.)	
		  [X]	1	| Описание товара 1 | "10    "	| 10,00
		  []	2	| Описание товара 2 | "20    "	| 40,00
		  []	3	| Описание товара 3 | "30    "	| 90,00
	  }
  }
  [Удалить]
  [Уведомить]
  [Оформить заказ] 
  
}
	
@endsalt