@startsalt
title Catalog page
{+
  Иванов Иван Иванович | {
  ^UserID^ Корзина^ Заказы^ Уведомления^
  }
  ----
  {^<b>Список Товаров:</b>
	  {SI
	  <b> ИД | <b> Описание товара | <b> Количество	| <b> Стоимость (руб.)	
		  1	| [] Описание товара 1 | "0   "
		  2	| [] Описание товара 2 | "0   "
		  3	| [] Описание товара 3 | "0   "
	  }
  }
  [Добавить в козину] 
  [Очистить]
}
	
@endsalt