@startsalt
title Messages page
{+
  Иванов Иван Иванович | {
  ^UserID^ Корзина^ Заказы^ Уведомления^
  }
  [Каталог]
  ----
  {^<b>Список товаров из подписки:</b>
	  {SI
	  <b> ИД | <b> Описание товара | <b> Количество на складе	| <b> Стоимость (руб.)	| Прочитано
		  [X]	1	| Описание товара 1 | "10    "	| 1,00  | [Не прочитано]
		  []	2	| Описание товара 2 | "20    "	| 2,00 | [Не прочитано]
		  []	3	| Описание товара 3 | "0    "	| 3,00 | [Прочитано]
	  }
  }
  [Отписаться]
  [Добавить в корзину] 
  
}
	
@endsalt