@startsalt
title Orders page
{+
  Иванов Иван Иванович | {
  ^UserID^ Корзина^ Заказы^ Уведомления^
  }
  [Каталог]
  ----
  {^<b>Список Заказов:</b>
	  {SI
	  {#
		<b> ИД	| <b> Стоимость (руб.)	| <b> Статус
		(X)	1 	| 10,00	| В работе
		()	2	| 2,00	| Ошибка оплаты
		()	3	| 3,00	| Новый
	}
	  }
  }
  ----
  {^<b>Список Товаров в Заказе 1:</b>
	  {SI
		{#
		<b>ИД | <b> Описание товара | <b> Количество | <b> Цена за ед. (руб.)
		[X] 1	| Описание товара 1 | "1   "	| 1,00
		[] 2	| Описание товара 2 | "2   "	| 2,00
		[X] 3	| Описание товара 3 | "3   "	| 3,00
		}
	  }
	    [<color:gray>Оплатить]|[<color:gray>Очистить]|[Повторить]|[Отменить]

  }


}
	
@endsalt