@startuml
hide empty description
title Состояния Заказа

[*] --> new : Новый
new --> checked : Проверено
checked --> work : В работе
work --> reserved : Зарезервировано
reserved --> paid : Оплачено
reserved --> error : Ошибка оплаты
paid --> [*]
new --> canceled : Отменено
checked --> canceled : Отменено
work --> canceled : Отменено
error --> work : Повторить
error --> canceled : Отменено
canceled --> [*]
@enduml