@startsalt
title Wellcome page
{+
  Иванов Иван Иванович | {
  ^UserID^ Корзина^ Заказы^ Уведомления^
  }
  [Каталог]
  ----
  {^<b>Список предыдущих покупок:</b>
	  {T!
		  <b> ИД продукта | <b> Описание | <b> Количество | <b> Стоимость (руб.)	
		  1	| Описание товара 1 | 10 | 10,00
		  2	| Описание товара 2 | 20 | 40,00
		  3	| Описание товара 3 | 30 | 90,00
	  }
  }
}
@endsalt